def mainDir="2-jenkins-docker"
def ecrLoginHelper="docker-credential-ecr-login"
def region="ap-northeast-2"
def ecrUrl="${ECR_URL}"
def repository="${ECR_REPOSITORY}"
def deployHost="${DEPLOY_HOST}"

pipeline {
    agent any

    stages {
        stage('===== Pull Codes from Github ====='){
            steps{
                checkout scm
            }
        }
        stage('===== Build Codes by Gradle =====') {
            steps {
                sh """
                cd ${mainDir}
                ./gradlew clean build
                """
            }
        }
        stage('===== Build Docker Image by Jib & Push to AWS ECR Repository =====') {
            steps {
                withAWS(region:"${region}", credentials:"aws-key") {
                    ecrLogin()
                    sh """
                        curl -O https://amazon-ecr-credential-helper-releases.s3.us-east-2.amazonaws.com/0.4.0/linux-amd64/${ecrLoginHelper}
                        chmod +x ${ecrLoginHelper}
                        mv ${ecrLoginHelper} /usr/local/bin/
                        cd ${mainDir}
                        ./gradlew jib -Djib.to.image=${ecrUrl}/${repository}:${currentBuild.number} -Djib.console='plain'
                    """
                }
            }
        }
        stage('===== Deploy to Private Server(test-deploy) =====') {
            steps{
                sshagent(credentials : ["deploy-key"]) {
                    sh "ssh -o StrictHostKeyChecking=no test-deploy@${deployHost} \
                     'aws ecr get-login-password --region ${region} | docker login --username AWS --password-stdin ${ecrUrl}/${repository}; \
                      docker rm -f jenkins-docker; \
                      docker run -d -p 80:8080 --name jenkins-docker -t ${ecrUrl}/${repository}:${currentBuild.number};'"
                }
            }
        }
    }
}
